[project]
name = "learning-fasthml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastlite>=0.2.4",
    "monsterui>=1.0.47",
    "numpy>=2.5.3",
    "pandas>=3.0.5",
    "plotly>=7.1.0",
    "python-fasthtml>=0.14.13",
]
